---
title: "Covid_19"
output: html_notebook
---

# Install package 
```{r}
require("COVID19")
```

# Some functions to use
```{r}
source("tools.R")
```

# countries

```{r} 
countries <- c("CHE", "FRA", "GBR","ESP","PRT","SVN","SVK", "DEU","DNK","BGR")
outcome   <- sapply(countries, function(x) {return(get_data(x))})
print(outcome)
```

```{r}
countries <- NULL
country   <- get_country_covid_19("CHE")
countries <- combine(countries, country)

country   <- get_country_covid_19("SYR")
print(country)
countries <- combine(countries, country)
print(countries)
```


# Switzerland 
```{r}

che_data = covid19(country = "CHE",
                   level = 1,
                   start = "2010-01-01", 
                   end = Sys.Date(),
                   raw = TRUE,
                   vintage = FALSE, 
                   verbose = FALSE,
                   cache = TRUE,
                   wb = NULL,
                   gmr = NULL,
                   amr = NULL)

che_data[is.na(che_data)] = 0
che_data[is.null(che_data)] = 0


recovered     <- che_data['recovered']/che_data[1:nrow(che_data),"population"]
deaths        <- che_data['deaths']/che_data[1:nrow(che_data),"population"]
confirmed     <- che_data['confirmed']/che_data[1:nrow(che_data),"population"]



rates         <- data.frame(recovered = recovered,
                            deaths  = deaths,
                            confirmed)

rates  <- apply(rates[-1],2,diff)
dates <- che_data[2:nrow(che_data),'date']
rates <- cbind(dates, rates)

che_data           <- as.data.frame(che_data[,c('date',
                                  'vaccines',
                                  'tests',
                                  'confirmed',
                                  'recovered',
                                  'deaths',
                                  'population',
                                  'latitude',
                                  'longitude')])

che_data[is.null(che_data)] = 0

che_rate_of_change <- as.data.frame(apply(che_data[-1],2,diff))
dim(che_rate_of_change)
summary(che_rate_of_change)

che_dates         <- che_data[2:nrow(che_data),"date"]
che_recovered     <- che_rate_of_change['recovered']/che_data[1:nrow(che_data),"population"]
che_deaths        <- che_rate_of_change['deaths']/che_data[1:nrow(che_data),"population"]
che_confirmed     <- che_rate_of_change['confirmed']/che_data[1:nrow(che_data),"population"]
che_latitude      <- che_data[2:nrow(che_data),"latitude"]
che_longitude     <- che_data[2:nrow(che_data),"longitude"]

che_rates         <- data.frame(date = che_dates,
                                confirmed = che_confirmed,
                                deaths    = che_deaths,
                                recovered = che_recovered,
                                latitude  = che_latitude,
                                longitude  = che_longitude)
che_rates
```
